# Generated by Django 5.0 on 2024-01-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45)),
                ('Email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=70)),
                ('password2', models.CharField(max_length=70)),
            ],
        ),
    ]
